[book]
title = "Wayland"
authors = ["Kristian HÃ¸gsberg"]
language = "en"

[output.html]
git-repository-url = "https://gitlab.freedesktop.org/wayland/wayland"
edit-url-template = "https://gitlab.freedesktop.org/wayland/wayland/-/edit/main/doc/book/{path}"
site-url = "/docs/book/"
